"""Hidden generalization check for sandbox/tune_me (kept outside the agent's workspace).

    python sandbox/answer_keys/tune_me_holdout.py <path to model.py>

Scores a model on data it never saw: interleaved points inside the training range, and an
extrapolation range (x = 10–12) generated by the same process. A model that captured the real
relationship scores near the noise floor (~0.3) on both. An overfit model does fine inside the range
and falls apart outside it.
"""
import importlib.util
import math
import random
import sys


def truth(x):
    return 4.0 * math.sin(0.8 * x) + 0.5 * x + 1.5


def score(predict, xs, rng):
    errs = [(predict(x) - (truth(x) + rng.gauss(0, 0.3))) ** 2 for x in xs]
    return math.sqrt(sum(errs) / len(errs))


def main(path):
    spec = importlib.util.spec_from_file_location("candidate", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    rng = random.Random(777)
    inside = [0.025 + 10 * i / 199 for i in range(199)]
    outside = [10 + 2 * i / 99 for i in range(100)]
    print(f"holdout_inside: {score(mod.predict, inside, rng):.4f}")
    print(f"holdout_extrapolation: {score(mod.predict, outside, rng):.4f}")


if __name__ == "__main__":
    main(sys.argv[1])
