"""Human-readable copies of a job's state in <workspace>/jobs/<slug>/.

The database is the source of truth; these files let people read along, or take over by hand.
They are regenerated on every change, except README.md, which is written once.
"""
from __future__ import annotations

import datetime as dt
import logging
from pathlib import Path

from .planner import children_map
from .scratchpad import render_markdown

log = logging.getLogger(__name__)

README = """# {title}

This folder belongs to a **LocalAgent job**: a long-running task the agent works on in the background.

- **Goal:** {goal}
- **Created:** {created}
- **Job id:** `{id}`

## What's in here
| File / folder | What it is | Safe to edit? |
|---|---|---|
| `README.md` | This explanation (written once) | Yes |
| `job.md` | Current status, budget used, and progress summary | No: regenerated by LocalAgent |
| `plan.md` | The plan: every task, its status, and results | No: regenerated. Edit the plan in the app |
| `journal.md` | Timeline of what happened and why | No: regenerated |
| `scratchpad.md` | The job's working memory: context notes, task list with checkboxes, task checklists. The agent reads it before every task | No: regenerated. Edit the context in the app |

The job's actual work (files it creates or changes) lives in the project workspace, usually next to this `jobs/`
folder, and is named in the task summaries in `plan.md`.

The job is controlled from the LocalAgent app (Start, Pause, Resume, Stop). Deleting this folder does not delete
the job; deleting the job in the app does not delete this folder.
"""

STATUS_MARK = {"done": "✅", "skipped": "⏭️", "failed": "❌", "running": "▶️", "waiting_user": "❓", "pending": "⬜"}


def job_dir(workspace: str | Path, job: dict) -> Path:
    return Path(workspace) / "jobs" / job["slug"]


def _fmt_time(ts: float | None) -> str:
    return dt.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M") if ts else "-"


def write_mirrors(jobs, store, job_id: str) -> None:
    try:
        job = jobs.get_job(job_id)
        project = store.get_project(job["project_id"]) if job else None
        if not job or not project:
            return
        folder = job_dir(project["workspace_path"], job)
        folder.mkdir(parents=True, exist_ok=True)
        readme = folder / "README.md"
        if not readme.exists():
            readme.write_text(README.format(title=job["title"], goal=job["goal"], created=_fmt_time(job["created_at"]),
                                            id=job["id"]), encoding="utf-8")
        tasks = jobs.list_tasks(job_id)
        (folder / "job.md").write_text(_job_md(job, tasks), encoding="utf-8")
        (folder / "plan.md").write_text(_plan_md(job, tasks), encoding="utf-8")
        (folder / "journal.md").write_text(_journal_md(job, jobs.list_journal(job_id)), encoding="utf-8")
        (folder / "scratchpad.md").write_text(render_markdown(job, tasks, jobs.list_context(job_id)), encoding="utf-8")
        _write_notes(folder, jobs.list_notes(job_id))
    except Exception:
        log.exception("could not write job mirrors for %s", job_id)


def _job_md(job: dict, tasks: list[dict]) -> str:
    budget, usage = job["budget"], job["usage"]
    limit = "no limit" if budget.get("indefinite") else f"{budget.get('max_hours')} h / {budget.get('max_steps')} steps"
    parents = {t["parent_key"] for t in tasks if t.get("parent_key")}
    leaf = [t for t in tasks if t["key"] not in parents]
    counts = {s: sum(1 for t in leaf if t["status"] == s) for s in STATUS_MARK}
    lines = [f"# {job['title']}", "", f"**Status:** {job['status']}" + (f" — {job['status_reason']}" if job.get("status_reason") else ""),
             f"**Goal:** {job['goal']}", "",
             f"**Budget:** {limit} · **Used:** {usage.get('seconds', 0) / 3600:.2f} h, {usage.get('steps', 0)} steps",
             f"**Updated:** {_fmt_time(job['updated_at'])}", "",
             "**Tasks:** " + ", ".join(f"{v} {k}" for k, v in counts.items() if v) if leaf else "**Tasks:** no plan yet"]
    return "\n".join(lines) + "\n"


def _plan_md(job: dict, tasks: list[dict]) -> str:
    if not tasks:
        return f"# Plan: {job['title']}\n\nNo plan yet.\n"
    kids = children_map(tasks)
    lines = [f"# Plan: {job['title']}", ""]

    def walk(parent, depth):
        for t in sorted(kids.get(parent, []), key=lambda x: x["position"]):
            indent = "  " * depth
            is_parent = t["key"] in kids
            mark = "" if is_parent else STATUS_MARK.get(t["status"], "⬜") + " "
            lines.append(f"{indent}- {mark}**[{t['key']}] {t['title']}**")
            if not is_parent:
                if t["done_when"]:
                    lines.append(f"{indent}  - Done when: {t['done_when']}")
                if t["attempts"]:
                    lines.append(f"{indent}  - Attempts: {t['attempts']} of {t['max_attempts']}")
                if t.get("result_summary"):
                    lines.append(f"{indent}  - Result: {t['result_summary']}")
                if t.get("question"):
                    lines.append(f"{indent}  - Waiting on the user: {t['question']}")
            walk(t["key"], depth + 1)

    walk(None, 0)
    return "\n".join(lines) + "\n"


def _write_notes(folder: Path, notes: list[dict]) -> None:
    if not notes:
        return
    notes_dir = folder / "notes"
    notes_dir.mkdir(exist_ok=True)
    by_source: dict[str, list[dict]] = {}
    for n in notes:
        by_source.setdefault(n["source"], []).append(n)
    for source, items in by_source.items():
        name = "".join(ch if ch.isalnum() or ch in "-_." else "_" for ch in source)[:120] + ".md"
        lines = [f"# Notes: {source}", ""]
        for n in items:
            loc = f" ({n['location']})" if n["location"] else ""
            lines += [f"- **[n{n['id']}]**{loc} {n['claim']}", f"  > {n['quote']}"]
        (notes_dir / name).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _journal_md(job: dict, entries: list[dict]) -> str:
    lines = [f"# Journal: {job['title']}", ""]
    for e in entries:
        task = f"[{e['task_key']}] " if e.get("task_key") else ""
        lines.append(f"- `{_fmt_time(e['created_at'])}` {task}{e['text']}")
    return "\n".join(lines) + "\n"
